/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * peminjaman_buku.java
 *
 * 
 */
package KELOMPOK_1;

import javax.swing.JOptionPane;

/**
 *
 *
 */
public class peminjamanBuku extends javax.swing.JFrame {
    
    pembayaran pe = new pembayaran();

    /** Creates new form peminjaman_buku */
    public peminjamanBuku() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        gambar = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        category = new javax.swing.JMenu();
        moduleItem = new javax.swing.JMenuItem();
        majalahItem = new javax.swing.JMenuItem();
        separatorCategory = new javax.swing.JPopupMenu.Separator();
        ComicItem = new javax.swing.JMenuItem();
        novelItem = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        tglPinjamItem = new javax.swing.JMenuItem();
        tglKembaliItem = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        pembayaranItem = new javax.swing.JMenuItem();
        exit1 = new javax.swing.JMenu();
        profile = new javax.swing.JMenuItem();
        delete_SB = new javax.swing.JMenuItem();
        report = new javax.swing.JMenu();
        exit = new javax.swing.JMenu();
        signOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("aplikasi -[ peminjaman buku ]-");

        Panel.setBackground(new java.awt.Color(0, 0, 0));

        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Copy of arcides.gif"))); // NOI18N

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gambar)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gambar)
        );

        MenuBar.setBackground(new java.awt.Color(0, 0, 0));
        MenuBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), java.awt.Color.black, new java.awt.Color(0, 0, 0)));
        MenuBar.setForeground(new java.awt.Color(51, 255, 0));

        category.setBackground(new java.awt.Color(0, 0, 0));
        category.setForeground(new java.awt.Color(255, 0, 0));
        category.setMnemonic('c');
        category.setText("Category     ");
        category.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 10)); // NOI18N

        moduleItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        moduleItem.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 10)); // NOI18N
        moduleItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buku.png"))); // NOI18N
        moduleItem.setText("  Module");
        moduleItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduleItemActionPerformed(evt);
            }
        });
        category.add(moduleItem);

        majalahItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        majalahItem.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 10)); // NOI18N
        majalahItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/novel.png"))); // NOI18N
        majalahItem.setText("  Majalah ");
        majalahItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majalahItemActionPerformed(evt);
            }
        });
        category.add(majalahItem);
        category.add(separatorCategory);

        ComicItem.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 10)); // NOI18N
        ComicItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/haha.png"))); // NOI18N
        ComicItem.setText("  Comic");
        ComicItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComicItemActionPerformed(evt);
            }
        });
        category.add(ComicItem);

        novelItem.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 10)); // NOI18N
        novelItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Copy of imges.jpg"))); // NOI18N
        novelItem.setText("  Novel");
        novelItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novelItemActionPerformed(evt);
            }
        });
        category.add(novelItem);

        MenuBar.add(category);

        transaksi.setBackground(new java.awt.Color(0, 0, 0));
        transaksi.setForeground(new java.awt.Color(255, 0, 0));
        transaksi.setMnemonic('t');
        transaksi.setText("Transaksi     ");
        transaksi.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 10)); // NOI18N

        tglPinjamItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        tglPinjamItem.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 10)); // NOI18N
        tglPinjamItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Copy of uparrowicon-1 copy.png"))); // NOI18N
        tglPinjamItem.setText("tgl Pinjam");
        tglPinjamItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglPinjamItemActionPerformed(evt);
            }
        });
        transaksi.add(tglPinjamItem);

        tglKembaliItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        tglKembaliItem.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 10)); // NOI18N
        tglKembaliItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bawah.png"))); // NOI18N
        tglKembaliItem.setText("tgl Kembali");
        tglKembaliItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglKembaliItemActionPerformed(evt);
            }
        });
        transaksi.add(tglKembaliItem);
        transaksi.add(separator);

        pembayaranItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        pembayaranItem.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 10)); // NOI18N
        pembayaranItem.setText("pemBayaran  ");
        pembayaranItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranItemActionPerformed(evt);
            }
        });
        transaksi.add(pembayaranItem);

        MenuBar.add(transaksi);

        exit1.setBackground(new java.awt.Color(0, 0, 0));
        exit1.setForeground(new java.awt.Color(255, 0, 0));
        exit1.setMnemonic('e');
        exit1.setText("Admin   ");
        exit1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 10)); // NOI18N

        profile.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 10)); // NOI18N
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/anger.png"))); // NOI18N
        profile.setText("profile Admin");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        exit1.add(profile);

        delete_SB.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 10)); // NOI18N
        delete_SB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/_ack8.png"))); // NOI18N
        delete_SB.setText("DELETE data sewa");
        delete_SB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_SBActionPerformed(evt);
            }
        });
        exit1.add(delete_SB);

        MenuBar.add(exit1);

        report.setBackground(new java.awt.Color(0, 0, 0));
        report.setForeground(new java.awt.Color(255, 0, 0));
        report.setMnemonic('r');
        report.setText("Report   ");
        report.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 10)); // NOI18N
        MenuBar.add(report);

        exit.setBackground(new java.awt.Color(0, 0, 0));
        exit.setForeground(new java.awt.Color(255, 0, 0));
        exit.setMnemonic('e');
        exit.setText("Exit");
        exit.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 10)); // NOI18N

        signOut.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 10)); // NOI18N
        signOut.setForeground(new java.awt.Color(0, 0, 255));
        signOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/es copy.png"))); // NOI18N
        signOut.setText("sigOut");
        signOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutActionPerformed(evt);
            }
        });
        exit.add(signOut);

        MenuBar.add(exit);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void signOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutActionPerformed
// sign out
    int logout = JOptionPane.showConfirmDialog(null, "sign out ?", "confirmasi keluar aplikasi",JOptionPane.YES_NO_OPTION);
    if (logout == JOptionPane.YES_OPTION){
        System.exit(0);
    }
}//GEN-LAST:event_signOutActionPerformed

private void moduleItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleItemActionPerformed
// module
   moduleFrame mF = new moduleFrame();
   mF.setVisible(true);
   dispose();
    
}//GEN-LAST:event_moduleItemActionPerformed

private void majalahItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majalahItemActionPerformed
// majalah
    majalahFrame mAF = new majalahFrame();
    mAF.setVisible(true);
    dispose();
}//GEN-LAST:event_majalahItemActionPerformed

private void ComicItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComicItemActionPerformed
// comic
    comicFrame cF = new comicFrame();
    cF.setVisible(true);
    dispose();
}//GEN-LAST:event_ComicItemActionPerformed

private void novelItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novelItemActionPerformed
// novel
    novelFrame nF = new novelFrame();
    nF.setVisible(true);
    dispose();
}//GEN-LAST:event_novelItemActionPerformed

private void tglPinjamItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglPinjamItemActionPerformed
// tgl pinjam
    tglPinjamFrame tPF = new tglPinjamFrame();
    tPF.setVisible(true);
    dispose();
}//GEN-LAST:event_tglPinjamItemActionPerformed

private void tglKembaliItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglKembaliItemActionPerformed
// tgl kembali
    tglKembaliFrame tKF = new tglKembaliFrame();
    tKF.setVisible(true);
    dispose();
}//GEN-LAST:event_tglKembaliItemActionPerformed

private void pembayaranItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranItemActionPerformed
// pembayaran
    pembayaranFrame pF = new pembayaranFrame();
    pF.setVisible(true);
    dispose();
}//GEN-LAST:event_pembayaranItemActionPerformed

private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
// profile
    profile p = new profile();
    p.setVisible(true);
    dispose();
}//GEN-LAST:event_profileActionPerformed

private void delete_SBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_SBActionPerformed
// delete sewa buku
    int delete = JOptionPane.showConfirmDialog(null, "delete semua DATA pinjam BUKU", "hapus data sewa buku ?",JOptionPane.YES_NO_OPTION);
    if (delete == JOptionPane.YES_OPTION){
        pe.delete();
        JOptionPane.showMessageDialog(null, "data sewa BUKU telah dihapus !");
    }
    
}//GEN-LAST:event_delete_SBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(peminjamanBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(peminjamanBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(peminjamanBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(peminjamanBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new peminjamanBuku().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ComicItem;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JPanel Panel;
    private javax.swing.JMenu category;
    private javax.swing.JMenuItem delete_SB;
    private javax.swing.JMenu exit;
    private javax.swing.JMenu exit1;
    private javax.swing.JLabel gambar;
    private javax.swing.JMenuItem majalahItem;
    private javax.swing.JMenuItem moduleItem;
    private javax.swing.JMenuItem novelItem;
    private javax.swing.JMenuItem pembayaranItem;
    private javax.swing.JMenuItem profile;
    private javax.swing.JMenu report;
    private javax.swing.JPopupMenu.Separator separator;
    private javax.swing.JPopupMenu.Separator separatorCategory;
    private javax.swing.JMenuItem signOut;
    private javax.swing.JMenuItem tglKembaliItem;
    private javax.swing.JMenuItem tglPinjamItem;
    private javax.swing.JMenu transaksi;
    // End of variables declaration//GEN-END:variables
}
