/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * profile.java
 *
 * 
 */
package KELOMPOK_1;

import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class profile extends javax.swing.JFrame {

    /** Creates new form profile */
    public profile() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        user = new javax.swing.JPanel();
        nama = new javax.swing.JLabel();
        online = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        onoffRadioButton = new javax.swing.JRadioButton();
        biodata = new javax.swing.JPanel();
        biodataNama = new javax.swing.JLabel();
        biodataNpm = new javax.swing.JLabel();
        biodataKelas = new javax.swing.JLabel();
        fb = new javax.swing.JLabel();
        twitter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("- [ profile ADMIN ] -");

        background.setBackground(new java.awt.Color(0, 0, 0));

        user.setBackground(new java.awt.Color(0, 0, 0));
        user.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        nama.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setText("Kelompok1");

        online.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/online.png"))); // NOI18N

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/images copy.png"))); // NOI18N
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        onoffRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        onoffRadioButton.setFont(new java.awt.Font("Chiller", 1, 18)); // NOI18N
        onoffRadioButton.setForeground(new java.awt.Color(204, 255, 255));
        onoffRadioButton.setText("online/ offline");

        biodata.setBackground(new java.awt.Color(0, 0, 0));
        biodata.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 204)));

        biodataNama.setFont(new java.awt.Font("Showcard Gothic", 0, 13)); // NOI18N
        biodataNama.setForeground(new java.awt.Color(252, 240, 240));
        biodataNama.setText("Nama : kelompok 1");

        biodataNpm.setFont(new java.awt.Font("Showcard Gothic", 0, 13)); // NOI18N
        biodataNpm.setForeground(new java.awt.Color(252, 240, 240));
        biodataNpm.setText("jenis anggoita   : umum");

        biodataKelas.setFont(new java.awt.Font("Showcard Gothic", 0, 13)); // NOI18N
        biodataKelas.setForeground(new java.awt.Color(252, 240, 240));
        biodataKelas.setText("tugas : java oop 2");

        javax.swing.GroupLayout biodataLayout = new javax.swing.GroupLayout(biodata);
        biodata.setLayout(biodataLayout);
        biodataLayout.setHorizontalGroup(
            biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biodataLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(biodataNpm)
                    .addComponent(biodataNama)
                    .addComponent(biodataKelas))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        biodataLayout.setVerticalGroup(
            biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biodataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(biodataKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(biodataNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(biodataNpm)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        fb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/FACEBOOK.png"))); // NOI18N
        fb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fbMouseClicked(evt);
            }
        });

        twitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/TWITTER.png"))); // NOI18N
        twitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twitterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout userLayout = new javax.swing.GroupLayout(user);
        user.setLayout(userLayout);
        userLayout.setHorizontalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userLayout.createSequentialGroup()
                        .addComponent(online)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nama))
                    .addGroup(userLayout.createSequentialGroup()
                        .addComponent(onoffRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fb)
                    .addComponent(twitter))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(biodata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        userLayout.setVerticalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userLayout.createSequentialGroup()
                        .addComponent(fb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(twitter))
                    .addGroup(userLayout.createSequentialGroup()
                        .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama)
                            .addComponent(online))
                        .addGap(11, 11, 11)
                        .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(homeButton, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(onoffRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(biodata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
// home
    peminjamanBuku pB = new peminjamanBuku();
    pB.setVisible(true);
    dispose();
}//GEN-LAST:event_homeButtonActionPerformed

private void fbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbMouseClicked
// facebook
  
}//GEN-LAST:event_fbMouseClicked

private void twitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twitterMouseClicked
// twitter
   
}//GEN-LAST:event_twitterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new profile().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel biodata;
    private javax.swing.JLabel biodataKelas;
    private javax.swing.JLabel biodataNama;
    private javax.swing.JLabel biodataNpm;
    private javax.swing.JLabel fb;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel online;
    private javax.swing.JRadioButton onoffRadioButton;
    private javax.swing.JLabel twitter;
    private javax.swing.JPanel user;
    // End of variables declaration//GEN-END:variables
}
