/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SignIn.java
 *
 *
 */
package KELOMPOK_1;

import javax.swing.JOptionPane;

/**
 *
 * @author Riki
 */
public class SignIn extends javax.swing.JFrame {

    /** Creates new form SignIn */
    public SignIn() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        signinButton = new javax.swing.JButton();
        CheckBox = new javax.swing.JCheckBox();
        IDpassword = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        pwdPasswordField = new javax.swing.JPasswordField();
        password1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[ Kelompok 1 ]");

        background.setBackground(new java.awt.Color(0, 0, 0));
        background.setToolTipText("");

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/image_java.png"))); // NOI18N

        signinButton.setFont(new java.awt.Font("Showcard Gothic", 1, 11)); // NOI18N
        signinButton.setText("sign in");
        signinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinButtonActionPerformed(evt);
            }
        });

        CheckBox.setBackground(new java.awt.Color(0, 0, 0));
        CheckBox.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        CheckBox.setForeground(new java.awt.Color(153, 153, 153));
        CheckBox.setText("keep me Sign in");

        IDpassword.setBackground(new java.awt.Color(0, 0, 0));
        IDpassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        IDpassword.setForeground(new java.awt.Color(255, 255, 255));
        IDpassword.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        IDpassword.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        user.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        user.setForeground(new java.awt.Color(153, 153, 153));
        user.setText("ID user");

        idTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        password.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        password.setForeground(new java.awt.Color(153, 153, 153));
        password.setText("password");

        pwdPasswordField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pwdPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdPasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IDpasswordLayout = new javax.swing.GroupLayout(IDpassword);
        IDpassword.setLayout(IDpasswordLayout);
        IDpasswordLayout.setHorizontalGroup(
            IDpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IDpasswordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        IDpasswordLayout.setVerticalGroup(
            IDpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IDpasswordLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(IDpasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password)
                    .addComponent(pwdPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        password1.setFont(new java.awt.Font("Fira Sans Book", 1, 11)); // NOI18N
        password1.setForeground(new java.awt.Color(153, 153, 153));
        password1.setText("Aplikasi Perpustakaan STMIK Amik Bandung");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckBox)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(signinButton)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addComponent(IDpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addComponent(password1)
                        .addGap(18, 18, 18))))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(IDpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(image)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signinButton)
                .addGap(18, 18, 18)
                .addComponent(CheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void signinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinButtonActionPerformed
// sign in
    if ((idTextField.getText().equals("kelompok1")) && 
            (String.valueOf(pwdPasswordField.getText()).equals("kelompok1"))){
        peminjamanBuku pb = new peminjamanBuku();
        pb.setVisible(true);
        dispose();
    } else {
        JOptionPane.showMessageDialog(null,"account  '' "+ idTextField.getText()+" ''  FAILED !", null,JOptionPane.WARNING_MESSAGE);
        idTextField.setText("");
        pwdPasswordField.setText("");
        idTextField.requestFocus();
    }
}//GEN-LAST:event_signinButtonActionPerformed

private void pwdPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdPasswordFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_pwdPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox;
    private javax.swing.JPanel IDpassword;
    private javax.swing.JPanel background;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel image;
    private javax.swing.JLabel password;
    private javax.swing.JLabel password1;
    private javax.swing.JPasswordField pwdPasswordField;
    private javax.swing.JButton signinButton;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
