/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * tgl_kembaliFrame.java
 *
 * 
 */
package KELOMPOK_1;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * 
 */
public class tglKembaliFrame extends javax.swing.JFrame {
    
    tglKembali tk = new tglKembali();
    tglPinjam tp = new tglPinjam();

    /** Creates new form tgl_kembaliFrame */
    public tglKembaliFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelButton = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        writeButton = new javax.swing.JButton();
        PanelModule = new javax.swing.JPanel();
        iDLabel = new javax.swing.JLabel();
        no_IDTextField = new javax.swing.JTextField();
        judulLabel = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tglComboBox = new javax.swing.JComboBox();
        bulanComboBox = new javax.swing.JComboBox();
        tahunComboBox = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablebuku = new javax.swing.JTable();
        prosesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[ Data transaksi ] tanggal pengembalian BUKU `");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        PanelButton.setBackground(new java.awt.Color(0, 0, 0));
        PanelButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)), javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0))));

        homeButton.setBackground(new java.awt.Color(0, 0, 0));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/images copy.png"))); // NOI18N
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("\" Tanggal pengembalian Buku ! \"");

        writeButton.setBackground(new java.awt.Color(0, 0, 0));
        writeButton.setFont(new java.awt.Font("Showcard Gothic", 1, 12)); // NOI18N
        writeButton.setForeground(new java.awt.Color(51, 255, 0));
        writeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon Corel_.png"))); // NOI18N
        writeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelButtonLayout = new javax.swing.GroupLayout(PanelButton);
        PanelButton.setLayout(PanelButtonLayout);
        PanelButtonLayout.setHorizontalGroup(
            PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(writeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        PanelButtonLayout.setVerticalGroup(
            PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelButtonLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(writeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelModule.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "pengembalian buku", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Showcard Gothic", 0, 12))); // NOI18N
        PanelModule.setFont(new java.awt.Font("Old English Text MT", 1, 11)); // NOI18N

        iDLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        iDLabel.setText("no ID peminjam");

        no_IDTextField.setEditable(false);
        no_IDTextField.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 10)); // NOI18N
        no_IDTextField.setForeground(new java.awt.Color(0, 0, 204));
        no_IDTextField.setText(" ");
        no_IDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_IDTextFieldActionPerformed(evt);
            }
        });

        judulLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        judulLabel.setText("nama peminjam");

        namaTextField.setEditable(false);
        namaTextField.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 11)); // NOI18N
        namaTextField.setForeground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Tanggal Kembali :");

        tglComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "tgl", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        bulanComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- bulan -", "January", "February", "Maret", "April", "Mey", "Juny", "July", "Agustus", "September", "October", "November", "Desember" }));

        tahunComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "tahun", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));

        tablebuku.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        tablebuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID buku", "Judul buku"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablebuku);
        if (tablebuku.getColumnModel().getColumnCount() > 0) {
            tablebuku.getColumnModel().getColumn(0).setMinWidth(1);
        }

        javax.swing.GroupLayout PanelModuleLayout = new javax.swing.GroupLayout(PanelModule);
        PanelModule.setLayout(PanelModuleLayout);
        PanelModuleLayout.setHorizontalGroup(
            PanelModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelModuleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addGroup(PanelModuleLayout.createSequentialGroup()
                        .addGroup(PanelModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iDLabel)
                            .addComponent(no_IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36)
                        .addGroup(PanelModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judulLabel)
                            .addGroup(PanelModuleLayout.createSequentialGroup()
                                .addComponent(tglComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bulanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tahunComboBox, 0, 65, Short.MAX_VALUE))
                            .addComponent(namaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))))
                .addContainerGap())
        );
        PanelModuleLayout.setVerticalGroup(
            PanelModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelModuleLayout.createSequentialGroup()
                .addGroup(PanelModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModuleLayout.createSequentialGroup()
                        .addComponent(judulLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(PanelModuleLayout.createSequentialGroup()
                        .addComponent(iDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(no_IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModuleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tglComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bulanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tahunComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        prosesButton.setBackground(new java.awt.Color(0, 0, 0));
        prosesButton.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        prosesButton.setForeground(new java.awt.Color(255, 255, 255));
        prosesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Love-message-icon.png"))); // NOI18N
        prosesButton.setText("proses");
        prosesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelModule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prosesButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prosesButton)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void no_IDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_IDTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_no_IDTextFieldActionPerformed

private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
// home
    peminjamanBuku pB = new peminjamanBuku();
    pB.setVisible(true);
    dispose();
}//GEN-LAST:event_homeButtonActionPerformed

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
// window activated
    tk.connect();
    tk.window();
    no_IDTextField.setText(tk.tp.no_id);
    namaTextField.setText(tk.tp.nama);
    
    DefaultTableModel tableBUKU = new DefaultTableModel();
        tableBUKU.addColumn("ID buku");
        tableBUKU.addColumn("judul buku");
        try {
            tk.connect();
            String sql = "SELECT * FROM sewa_buku";
            ResultSet rs = tk.st.executeQuery(sql);
            while(rs.next()){
                tableBUKU.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Failed - progress BUKU");
        }
    tablebuku.setModel(tableBUKU);
    
}//GEN-LAST:event_formWindowActivated

private void writeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeButtonActionPerformed
// write
    tglComboBox.setSelectedIndex(0);
    bulanComboBox.setSelectedIndex(0);
    tahunComboBox.setSelectedIndex(0);
}//GEN-LAST:event_writeButtonActionPerformed

private void prosesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesButtonActionPerformed
// prosses
    tk.connect();
    tk.no_id_tk = no_IDTextField.getText();
    tk.nama_tk = namaTextField.getText();
    String a = tablebuku.getValueAt(0, 0).toString();
    String b = tablebuku.getValueAt(0, 1).toString();
    tk.id_buku = a;
    tk.judul_buku = b;
    tk.date = tglComboBox.getSelectedItem().toString()+" "+
            bulanComboBox.getSelectedItem().toString()+" "+
            tahunComboBox.getSelectedItem().toString();
    
    tk.prosses();
    no_IDTextField.requestFocus();
}//GEN-LAST:event_prosesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tglKembaliFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tglKembaliFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tglKembaliFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tglKembaliFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new tglKembaliFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelButton;
    private javax.swing.JPanel PanelModule;
    private javax.swing.JComboBox bulanComboBox;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel iDLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField no_IDTextField;
    private javax.swing.JButton prosesButton;
    private javax.swing.JTable tablebuku;
    private javax.swing.JComboBox tahunComboBox;
    private javax.swing.JComboBox tglComboBox;
    private javax.swing.JButton writeButton;
    // End of variables declaration//GEN-END:variables
}
